CREATE TABLE `house_info` (
  `id` bigint(64) NOT NULL,
  `city` varchar(20) NOT NULL COMMENT '城市',
  `region` varchar(20) NOT NULL COMMENT '区域',
  `name` varchar(20) NOT NULL COMMENT '名称',
  `address` varchar(100) NOT NULL COMMENT '地址',
  `lng` double NOT NULL COMMENT '经度',
  `lat` double NOT NULL COMMENT '纬度',
  `estate_type` varchar(10) NOT NULL COMMENT '物业类型',
  `house_num` varchar(10) NOT NULL COMMENT '楼栋',
  `room_num` varchar(10) NOT NULL COMMENT '室号',
  `floor` int(4) NOT NULL COMMENT '当前楼层',
  `height` int(4) NOT NULL COMMENT '总共层数',
  `area` double NOT NULL COMMENT '面积',
  `room_count` int(4) NOT NULL COMMENT '几室',
  `hall_count` int(4) NOT NULL COMMENT '几厅',
  `rent` int(4) NOT NULL COMMENT '租金,单位元',
  `purchase_date` datetime DEFAULT NULL COMMENT '购入时间',
  `purchase_price` int(4) NOT NULL COMMENT '购入价格,单位元',
  `price` int(4) NOT NULL COMMENT '评估单价,单位元',
  `total_price` int(4) NOT NULL COMMENT '评估总价,单位元',
  `eval_date` datetime NOT NULL COMMENT '评估时间',
  `live_status` varchar(10) NOT NULL COMMENT '居住状态（自住,父母住,子女住,出租,空置）',
  `remove_status` int(4) NOT NULL COMMENT '是否删除 0正常  1删除',
  `uid` varchar(50) NOT NULL COMMENT '用户ID',
  `eid` bigint(64) NOT NULL COMMENT '企业ID',
  `level` int(4) NOT NULL COMMENT '房产等级（1:豪宅级、2:公寓级、3:平房级、4:草屋级、5:山洞级）',
  `growth_rate` double NOT NULL COMMENT '复合增长率',
  `appreciation` int(4) NOT NULL COMMENT '房屋已升值',
  `rose_ranking` double NOT NULL COMMENT '均价排名涨幅',
  `avgprice_ranking` double NOT NULL COMMENT '均价排名均价',
  `rental_ratio` varchar(10) NOT NULL COMMENT '租售比（1:650）',
  `max_loan_money` double NOT NULL COMMENT '最高可贷,单位万元',
  `tag` varchar(50) NOT NULL COMMENT '小区标签,下环线分割',
  `liquidity_rating` int(4) NOT NULL COMMENT '流动性评级(0:0-20很差, 1:20-40较差, 2:40-60一般, 3:60-80良好 4:80-100很好)',
  `one_year_total_price` int(4) NOT NULL COMMENT '一年前的总价',
  `house_room_num` varchar(30) NOT NULL COMMENT '楼栋室号联合字段',
  `lease_start_date` date DEFAULT NULL COMMENT '起租日期',
  `lease_end_date` date DEFAULT NULL COMMENT '到期日期',
  `rent_cycle` int(4) DEFAULT NULL COMMENT '收租周期',
  `rent_cycle_unit` char(1) DEFAULT NULL COMMENT '收租周期单位(年，季，月)',
  `last_rent_date` date DEFAULT NULL COMMENT '下次收租日期',
  `min_sell_price` int(4) DEFAULT NULL COMMENT '城市相对最低均价',
  `max_sell_price` int(4) DEFAULT NULL COMMENT '城市相对最高均价',
  `total_score` double DEFAULT NULL COMMENT '流动性评级得分',
  `min_advice_value` double DEFAULT NULL COMMENT '挂牌建议总价下限',
  `max_advice_value` double DEFAULT NULL COMMENT '挂牌建议总价上限',
  `add_date` datetime NOT NULL COMMENT '添加时间',
  PRIMARY KEY (`id`,`remove_status`),
  KEY `eid_uid_status_idx` (`eid`,`uid`,`remove_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='我的房产信息表'